#!/bin/sh

{
  printf -- '---\n'
  printf 'title: tom@skala\n'
  printf -- '---\n'
  printf '\n'
} > index.md

find posts -maxdepth 1 -type f -name '*.md' | sort -r | while read -r f; do
  datepart=$(printf '%s' "${f}" | sed -n 's|.*/\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\).*|\1/\2/\3|p')
  title=$(sed -n 's/^title: *\(.*\)$/\1/p' "${f}")
  published=$(sed -n 's|^date: *\([0-9]\{4\}/[0-9]\{2\}/[0-9]\{2\}\)$|\1|p' "${f}")

  # No .html extension: assumes that nginx knows how to append it.
  # This makes for nicer looking URLs.
  html="${f%.md}"
  printf '* %s [%s](%s)\n' "${published}" "${title}" "${html}" >> index.md

  if [ -z "${datepart}" ]; then
    printf 'WARNING: No date found in file name %s\n' "${f}" >&2
  fi

  if [ -z "${title}" ]; then
    printf 'WARNING: No title found in file %s\n' "${f}" >&2
  fi

  if [ -z "${published}" ]; then
    printf 'WARNING: No date found in file %s\n' "${f}" >&2
  fi

  if [ "${datepart}" != "${published}" ]; then
    printf 'WARNING: Date mismatch between file name and contents of %s\n' "${f}" >&2
  fi
done
