#!/bin/sh

{
  printf -- '---\n'
  printf 'title: tom@skala\n'
  printf -- '---\n'
  printf '\n'
} > index.md

for f in posts/*.md; do
  title=$(sed -n 's/^title: *\(.*\)$/\1/p' "${f}")
  published=$(sed -n 's/^date: *\(.*\)$/\1/p' "${f}")
  html="${f%.md}.html"
  printf '* %s [%s](%s)\n' "${published}" "${title}" "${html}" >> index.md

  if [ -z "${title}" ]; then
    printf 'Warning: No title found in file %s\n' "${f}" >&2
  fi

  if [ -z "${published}" ]; then
    printf 'Warning: No date found in file %s\n' "${f}" >&2
  fi
done
